sudo: false

language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

-before_install:
  - phpenv global 5.5
  - composer require codeclimate/php-test-reporter --dev
  - phpenv global "$TRAVIS_PHP_VERSION"
  
script: ./vendor/bin/phpunit --coverage-text
